version: '3'
volumes:
  fhirdata:
    driver: local
services:
  mongo:
    image: library/mongo:4.2
    volumes:
      - fhirdata:/data/db
    restart: always
  fhir_repo:
    build: .
    environment:
      - APP_CONF_FILE=/fhir/conf/application-docker.conf
      - LOGBACK_CONF_FILE=/fhir/conf/logback.xml
      - FHIR_ROOT_URL=http://fhir.srdc.com.tr
      - LOG_LEVEL=INFO
    ports:
      - "8080:8080"
    volumes:
      - ./fhir:${path-to-fhir-configuration-directory}
    restart: always
